// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Izqalan Nor'Izad",
            "url": "https://github.com/izqalan",
            "email": "izqalan@duck.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/candidate": {
            "post": {
                "description": "Create a new candidate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidate"
                ],
                "summary": "Create Candidate",
                "responses": {
                    "200": {
                        "description": "Candidate created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/election": {
            "post": {
                "description": "Create a new election",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election"
                ],
                "summary": "Create Election",
                "responses": {
                    "200": {
                        "description": "Election created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/election/{electionID}": {
            "get": {
                "description": "Get election by electionID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election"
                ],
                "summary": "Get Election",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Election ID",
                        "name": "electionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Election created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/hello": {
            "get": {
                "description": "Returns hello world",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Signal"
                ],
                "summary": "Hello World",
                "responses": {
                    "200": {
                        "description": "hello world",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Returns pong",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Signal"
                ],
                "summary": "Ping Pong",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Fabric Voting API",
	Description:      "A Voting DLT service API in Go using Gin framework.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
